### PR TITLE
Bump LibreSSL to 3.4.1

### PR DESCRIPTION
**Pull request by itZzenXX**
Signed-off-by: itZzenXX <codeberg.giovanni@aleeas.com>

### CODE REVIEW

**Comment by CaseOf** [comment]
Did you know you can edit your commit with git  commit --amend and then force push it with git push --force to update your original pull?
If not, now you know 😉
I will try to merge that later today

**Comment by orbea** [comment]
@itZzenXX Maybe we shouldn't drop the 3.3.5 series yet.

**Comment by itZzenXX** [comment]
On second thought, yeah we shouldn't. But we should still drop LibreSSL 3.4.0 because it's a dev release.

**Comment by orbea** [comment]
> But we should still drop LibreSSL 3.4.0 because it's a dev release.

Sounds fine to me.

**Pull request closed without merging**
