### PR TITLE
mail-mta/opensmtpd: new package, add 6.8.0_p2-r2

### PR DESCRIPTION
**Pull request by CyberTailor**
Version constraint in ::gentoo conflicts with dev-libs/openssl::libressl

### CODE REVIEW

**Comment by orbea** [comment]
Shouldn't this be fixed in the dummy openssl package?

https://github.com/gentoo/libressl/tree/master/dev-libs/openssl

**Comment by CyberTailor** [comment]
```sh
# < openssl 3 for bug #881701
DEPEND="
	acct-user/smtpd
	acct-user/smtpq
	<dev-libs/openssl-3:=
```

**Comment by CyberTailor** [comment]
> Shouldn't this be fixed in the dummy openssl package?
Dummy package versioning scheme could be changed to mimic 1.1.1 openssl version

**Comment by orbea** [comment]
Perhaps I shouldn't of removed the `2.9.2` ebuild here?

https://github.com/gentoo/libressl/commit/9b64869ea228c3915feb5027f95a6292d94896eb

**Pull request closed without merging**
