### PR TITLE
Change patch for dev-qt/qtnetwork-5.11.2 and add dev-qt/qtnetwork-5.11.3

### PR DESCRIPTION
**Pull request by sklv**
Not sure if this is compatible with libressl >2.6 but this is at least a starting point.

### CODE REVIEW

**Comment by ian-moone** [comment]
This is a regression at least for libressl 2.8.2 users. I tried to rebuild `dev-qt/qtnetwork-5.11.2`, but unfortunately I got:

```
.obj/qsslellipticcurve_openssl.o ssl/qsslellipticcurve_openssl.cpp
ssl/qsslsocket_openssl_symbols.cpp:194:26: error: cannot initialize return object of type 'BIO_METHOD *'
      (aka 'bio_method_st *') with an rvalue of type 'const BIO_METHOD *' (aka 'const bio_method_st *')
DEFINEFUNC(BIO_METHOD *, BIO_s_mem, void, DUMMYARG, return 0, return)
~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ssl/qsslsocket_openssl_symbols_p.h:185:33: note: expanded from macro 'DEFINEFUNC'
    ret q_##func(arg) { funcret func(a); }
                                ^~~~~~~
1 error generated.
make: *** [Makefile:23575: .obj/qsslsocket_openssl_symbols.o] Error 1
```

Reverting the commit builds fine.

**Comment by ian-moone** [comment]
As I suspected, `dev-qt/qtnetwork-5.11.3` is also affected, same as above. Using the early patch for 5.11.2, works just fine.

**Comment by blueness** [comment]
close this once you're satisfied everything is okay

**Comment by blueness** [comment]
i think we're done here.

**Pull request closed without merging**
