### PR TITLE
bump dev-libs/libressl to version 3.3.3

### PR DESCRIPTION
**Pull request by itZzenXX**

### CODE REVIEW

**Comment by CaseOf** [comment]
Hi, can you merge your two commits into a single one, please?

**Comment by itZzenXX** [comment]
Ok, doing that now

**Comment by itZzenXX** [comment]
Imma just make a new pull request to make one commit

**Comment by CaseOf** [comment]
you can use `git rebase` too.

**Comment by itZzenXX** [comment]
is there a guide? Idk how to use git rebase haha

**Comment by CaseOf** [comment]
https://git-scm.com/docs/git-rebase

**Comment by itZzenXX** [comment]
thanks!

**Pull request closed without merging**
