### PR TITLE
Add/Update some ebuilds for LibreSSL >= 2.3.0

### PR DESCRIPTION
**Pull request by csmk**
All patches are from FreeBSD ports. A big thank you to them! :+1:

### CODE REVIEW

**Comment by blueness** [comment]
i pitch hitting for hasufell.  i don't get why i'm getting that "all checks have failed" for travis ci.  any clue since i'd like to start honoring these pull requests.  its apparently happening to all of them.

**Comment by Sp1l** [comment]
@csmk Make sure you check both https://wiki.freebsd.org/LibreSSL/Ports and https://wiki.freebsd.org/OpenSSL/No-SSLv3 . No-SSLv3 is not a LibreSSL issue, you can have the same problem when you decide to build OpenSSL -nossl3

**Comment by blueness** [comment]
@csmk @Sp1l is this ready to be merged?

**Comment by csmk** [comment]
@Sp1l Sure. I checked both.

@blueness Yes. It's _ready!_

**Comment by blueness** [comment]
I made some commits so your branch has conflicts.  You'll have to fix these first.

**Comment by csmk** [comment]
@blueness Conflicts resolved.

**Comment by blueness** [comment]
Okay this was a big merge, so please make sure everything is okay.

**Pull request merged**
