### PR TITLE
Updated OpenSSL Dummy Ebuild.

### PR DESCRIPTION
**Pull request by lluixhi**

### CODE REVIEW

**Comment by jlec** [comment]
What is this about? This doesn't make sense because it would force every science overlay user to use libressl.

**Comment by lluixhi** [comment]
All packages that depend on openssl right now need to point to virtual/openssl, and they don't.

@hasufell should we be fixing ebuilds to point to virtual/openssl instead of using a dummy ebuild?

**Comment by jlec** [comment]
Send pullrequests to fix the dependencies. This ebuild doesn't make sense all. Still you didn't provide any reason why everyone should use libressl and doesn't have any choice to install openssl.

**Comment by jlec** [comment]
Args, Forget all my comments. This is the libressl overlay.

**Comment by thotypous** [comment]
Should we really use unstable keywords like "~x86 ~amd64" while the keywords for the same version of the package in Portage are stable ("x86 amd64")? I have a server running a stable system and it is really cumbersome to manually add entries like `=dev-libs/openssl-1.0.1k ~amd64` to `/etc/portage/package.keywords`. I think the flags should be the same as the original package - if the user adds the overlay to her system, it means she wants to use the overlay -- no additional steps should be required.

**Comment by lluixhi** [comment]
No, we probably shouldnt.

**Pull request merged**
