### PR TITLE
Bump LibreSSL to 3.3.4, Stabalize 3.2.6, Drop old LibreSSL ebuilds

### PR DESCRIPTION
**Pull request by itZzenXX**

### CODE REVIEW

**Comment by orbea** [comment]
By any chance have you already checked if any of the existing workarounds can be removed after this?

**Comment by itZzenXX** [comment]
things in the files dir?

**Comment by orbea** [comment]
I meant the other ebuilds in this repo, maybe ` dev-python/m2crypto`?

**Comment by itZzenXX** [comment]
ok, will try to build m2crypto on LibreSSL 3.3.4.

**Comment by orbea** [comment]
Note that m2crypto builds with libressl, but with undefined references that break the builds that depend on m2crypto as described in issue https://github.com/gentoo/libressl/issues/335.

However that was only one possible example, there might be others? I will also try to check more when I have energy and time.

**Comment by itZzenXX** [comment]
m2crypto patch is still needed as a app with it as a dependency still failed.

**Comment by itZzenXX** [comment]
yeah, 3.4.x branch could bring some fixes to these software. I'll test when those come out and bump them to the overlay.

**Pull request closed without merging**
