### PR TITLE
net-libs/serf: version bump to 1.3.9

### PR DESCRIPTION
**Pull request by callmetango**
* added libressl patch of Alpine Linux

### CODE REVIEW

**Comment by blueness** [comment]
We do we need a patch from Alpine?

**Comment by steils** [comment]
The same question here. I have net-libs/serf-1.3.9 installed with libressl-2.9.1 from the main Gentoo tree with no additional patches.

**Comment by blueness** [comment]
@callmetango was this meant for the musl overlay given that Alpine is musl based?

**Comment by callmetango** [comment]
Sorry for the confusion. I will create another merge request with a better commit message.

**Pull request closed without merging**
