### PR TITLE
Bump boost to 1.60.0 for libressl overlay users, to be able to upgrade.

### PR DESCRIPTION
**Pull request by gled-rs**
Just adding boost-1.60.0 with the no-ssl3 patch. 

Compiles and run fine here.

### CODE REVIEW

**Comment by lluixhi** [comment]
@gled-rs
I thought boost 1.60+ already had the no sslv3 patch?

boost 1.60 was released on December 13, 2015
The patch that applied the libressl patch was
https://github.com/boostorg/asio/commit/bae401b1eb0594932c4e780d496cba852c23b75f#diff-adbfaa8a571120445d519fe4fa558c41
on December 10, 2015

Or will it not be included until 1.61.0?

**Comment by gled-rs** [comment]
Good question, need to check, I just patched the ebuild and compiled it locally.

**Comment by gled-rs** [comment]
removed the unneeded patch,compiles fine and works ok here, thanks for the heads-up @lluixhi !

**Comment by blueness** [comment]
i'm not using these packages so let me know if anything is broken.

**Comment by lluixhi** [comment]
@blueness 
The only difference between this ebuild and the ebuild in the tree is the EAPI version.. I don't think we needed to merge this.

**Comment by blueness** [comment]
so do we drop these packages altogether?  if so, produce a pr and i'll merge it.

**Pull request merged**
