### PR TITLE
qtnetwork 5.6.1 libressl keyword

### PR DESCRIPTION
**Pull request by gled-rs**
bump qtnetwork to 5.6.1

Compiles OK on my system.

### CODE REVIEW

**Comment by csmk** [comment]
The AUX, EBUILD and MISC in the Manifest file isn't required. The libressl overlay use thin-manifests, as you can see here: https://github.com/gentoo/libressl/blob/master/metadata/layout.conf

**Comment by gled-rs** [comment]
thin manifest commited.

**Comment by lluixhi** [comment]
One more thing -- can you quash these into one commit, drop the Changelogs, and make sure the qtnetwork-5.6.1.ebuild matches the one in the tree as closely as possible (minus the libressl patch)? Just preference. I don't think we're keeping Changelogs in this repo, it's easier to look at the differences in the future if the ebuilds are really close, and quashing the commits just keeps the commit history fairly neat.

**Comment by csmk** [comment]
qtnetwork 5.6.1 is stable in the tree.

Also, I made some [cosmetic changes in the ebuild](https://gist.github.com/csmk/b1740132aa8ed27352d5e1ef3f41b061) as suggested by repoman.

**Pull request merged**
