### PR TITLE
patch to make node.js 8.1.0 work with libressl.

### PR DESCRIPTION
**Pull request by Nazgolze**
Hi guys,

I've gotten node.js 8.1.0 to work with libressl on my home system and didn't want to hog all the fun. Let me know what you all think. I'm willing to make changes/fixes so that it's acceptable to the rest of the world

Juan

### CODE REVIEW

**Comment by blueness** [comment]
pushed

**Comment by csmk** [comment]
@Nazgolze, could you try to push this patch upstream? They have a [WIP](https://github.com/nodejs/node/pull/9376), but seems to be stalled.

**Comment by Nazgolze** [comment]
@csmk oh that is really cool. I thought they had decided to not support
LibreSSL, but it looks like that has changed. I will definitely look at
contributing upstream, thanks for pointing me in the right direction

**Comment by Nazgolze** [comment]
@csmk oh that is really cool. I thought they had decided to not support LibreSSL, but it looks like that has changed. I will definitely look at contributing upstream, thanks for pointing me in the right direction

**Pull request closed without merging**
