### PR TITLE
Update nodejs

### PR DESCRIPTION
**Pull request by pigfoot**

### CODE REVIEW

**Comment by lluixhi** [comment]
Just a note, that libressl patch is still broken. The crypto stuff works, but some TLS tests still fail.

**Comment by blueness** [comment]
i'd rather not push something broken to the overlay.

**Comment by pigfoot** [comment]
Understood. It makes sense.

**Comment by soredake** [comment]
https://github.com/nodejs/node/pull/9376

**Comment by dorvan** [comment]
please fix this!!!!!

**Comment by jbergstroem** [comment]
I think the best course of action wrt libressl is to not support it at all at the moment.

**Comment by jbergstroem** [comment]
This should probably target v6 (new LTS) and v7 as well. deps needs to be bumped.

**Comment by dorvan** [comment]
so it's not possible in libressl gentoo system use nodejs? any workaround?

**Comment by jbergstroem** [comment]
@dorvan the current state of libressl support in node.js is a very fresh patch that makes it build but also disables some functionality. You will likely also have issues with a system that has both libressl and openssl installed from npm or the test suite (makes assumptions about `openssl`). What I'm saying is that I think its a bit premature to just include the patch that makes it build and "be done with it". I guess it could be part of a masked package so people can test it out.

**Comment by dorvan** [comment]
@jbergstroem my comment it's not regarding nodejs in the gentoo/libressl project, but on other distros libressl implementation it's a production reality not only on nodejs but on another problematic/core deps/frequently used packages. looking to frequently used and state-of-art or mainstream packages thay need a priority and a stability about the system profile coherence. Otherwise the risk is to remake the same quest of perl and python migration of 2004/2007 before the definitive design of system infrastructure with python eselect switch (causing looses in community on both developers and users side). or libressl migration can be more "flexible" where openssl and libress can find place on the same system, switching application(for package)/library with an eselect or have to be more convinced and fast.   other ways can be like the icu lib update that impacts of the functionalities and coherence of all the installed system, make it broken with any simple maintenance action.

**Comment by jbergstroem** [comment]
@dorvan: I'm not sure what you're talking about. All I'm trying to to is to explain the current level of support for libressl in node since I happen to have a pretty good insight in that situation (being a node.js developer and part of the build infra team).

**Comment by csmk** [comment]
As an alternative you can use the bundled openssl, but [some people](https://github.com/gentoo/gentoo/pull/2693#issuecomment-257240369) say that this is not safe(?). For me is ok, though.

Check my overlay for [nodejs ebuilds](https://github.com/csmk/frabjous/tree/master/net-libs/nodejs), which has the `bundled-openssl` USE flag.

**Comment by pigfoot** [comment]
Close due to #154

**Pull request closed without merging**
