### PR TITLE
dev-lang/botan: Adding libressl support

### PR DESCRIPTION
**Pull request by waltercool**
I been using dev-lang/botan with this ebuild modification since a while and I haven't seen a compilation problem after all this time.

Feel free to review and merge if possible.

### CODE REVIEW

**Comment by blueness** [comment]
I can add this directly to the tree.  Is there anything subtle I should be aware of, or is it just a matter of adding 

`+        !libressl? ( >=dev-libs/openssl-0.9.8g:0[bindist=] )
 +        libressl? ( dev-libs/libressl )`

**Comment by waltercool** [comment]
At least I been using it since 1.10.12 to 1.10.15 without any kind of patch except adding the USE flag libressl. Under my experience I haven't seen any kind of behavior related with Botan and no build crash neither.

No, the version restriction was just a copy-paste from an older version, my bad, should be the same restriction for openssl at upstream, let me update it

**Comment by waltercool** [comment]
OK, I updated the commit removing the old versions not supported on upstream (.12 and .13) and updated .14 and .15 openssl restrictions to upstream current ebuild.

**Comment by waltercool** [comment]
Adding build log FYI

[build.txt](https://github.com/gentoo/libressl/files/724160/build.txt)

**Comment by blueness** [comment]
I just looked in the tree and =dev-libs/botan-2.0.1 already has the libressl USE flag.  I take it you want it backported to 1.10.14 and 1.10.15?  Since 1.10.14 is stable is it sufficient to just add it to 1.10.15?

**Comment by waltercool** [comment]
Botan 2 is masked at upstream due API breakages, so, 1.10.x is available for now.

If you want, I can make an update to this PR to only affect 1.10.15, so we don't affect an already tested and stable ebuild, and keeping any issue as part of unstable, would that makes sense?

**Comment by blueness** [comment]
I added libressl support to botan-1.10.15-r1.ebuild  which is in the main tree.  I'm trying to clean out the overlay so we can drop it altogether.

**Comment by waltercool** [comment]
Great, thanks.

**Comment by blueness** [comment]
sorry i forgot to push.  it should have landed in the tree now.

**Pull request closed without merging**
