### PR TITLE
net-libs/nodejs: Version 8.15.0

### PR DESCRIPTION
**Pull request by steils**

### CODE REVIEW

**Comment by blueness** [comment]
is this still needed? i just pushed PR 280 that seems to address the same issue.  i pushed that before i saw yours (sorry).  can you review commit a2e24e5339aa7 and make sure it doesn't miss anything.

**Comment by steils** [comment]
Hi @blueness 
Sure, this PR is still needed. #280 is for nodejs 10.*, mine is for 8.*.

**Comment by blueness** [comment]
ah okay.  i don't know nodejs so i thought 10.* makes 8.* obsolete.   anyhow, this is pushed.  thanks for the contribution.

**Comment by steils** [comment]
JFYI, currently 6.x, 8.x, 10.x and 11.x are supported:
https://github.com/nodejs/Release#release-schedule
All these branches are updated in the main Gentoo tree.

**Pull request closed without merging**
