### PR TITLE
dev-lang/rust-1.31.0: Add support for libressl 2.8.2

### PR DESCRIPTION
**Pull request by maurerpe**

### CODE REVIEW

**Comment by blueness** [comment]
please fix the metadata.xml, its throwing a travis error.

**Comment by maurerpe** [comment]
My mistake.  I should have ran repoman before commiting.  It is fixed now.

**Comment by blueness** [comment]
i can't apply this because the mudf was already added and this is causing a conflict.  can you make each PR about one and only one package/issue and squash together your commit against dev-lang/rust into just one commit.

**Comment by maurerpe** [comment]
Travis is giving me a weird error.  I am starting a new pull request.

**Pull request closed without merging**
