### PR TITLE
dev-util/cargo-c: new package, add 0.9.27

### PR DESCRIPTION
**Pull request by CyberTailor**
Bug: https://bugs.gentoo.org/917530

### CODE REVIEW

**Comment by orbea** [comment]
Thanks for the patch, but as the linked issue claims we are patching this. You can see an example here:


https://github.com/gentoo/libressl/blob/51827245cffe79459a2fa378a34738952926ed6c/dev-util/maturin/files/maturin-1.1.0-libressl-openssl-sys.patch
https://github.com/gentoo/libressl/blob/51827245cffe79459a2fa378a34738952926ed6c/dev-util/maturin/maturin-1.3.1.ebuild#L419-L421

The problem is that this crate is vendored in a lot of places and it would be an extreme burden to fix it everywhere and then rebase the fix for every new ebuild in ::gentoo so we are currently only fixing those users are interested in.

Also the issue is wrong about the openssl-sys crate having good reasons, I have never once seen it fail to build because of newer libressl versions except for this extremely inane version check.

**Comment by CyberTailor** [comment]
> but as the linked issue claims we are patching this

This is a real PITA to do, I'd prefer the less painful approach.

> so we are currently only fixing those users are interested in

I need cargo-c to build `media-gfx/libimagequant` and `sys-libs/pkgcraft`.

> I have never once seen it fail to build because of newer libressl versions

It could build but work incorrectly.
https://github.com/sfackler/rust-openssl/pull/2035

**Comment by orbea** [comment]
> I need cargo-c to build `media-gfx/libimagequant` and `sys-libs/pkgcraft`.

No disagreement with fixing this, I was just explaining why it hasn't already been fixed and why all the other examples aren't being actively fixed. When there is interest as you have shown now they can be fixed.

> This is a real PITA to do, I'd prefer the less painful approach.

The whole point of this repo is to use libressl and not a vendored openssl, but the patch only takes a moment to spin up.

> It could build but work incorrectly.

I have yet to see this be a problem in practice, but if you know any examples?

**Comment by orbea** [comment]
@CyberTailor I added cargo-c. https://github.com/gentoo/libressl/commit/93caad127d1d61e08a2507c07e5f075672756578

**Pull request closed without merging**
