### PR TITLE
Add net-dns/ldns-utils

### PR DESCRIPTION
**Pull request by csmk**
The ldns-utils doesn't build with ssl USE flag, so I commented out the ENGINE_load_cryptodev as the guys from Voidlinux did (https://github.com/voidlinux/void-packages/blob/master/srcpkgs/ldns/patches/libressl.patch).

Similar problem: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=191853

### CODE REVIEW

**Comment by hasufell** [comment]
oh, I missed this
I'll take a look

**Comment by hasufell** [comment]
The freebsd patch looks better: https://svnweb.freebsd.org/ports/head/dns/ldns/files/patch-examples_ldns-signzone.c?revision=379920&view=markup&pathrev=379920

**Comment by hasufell** [comment]
That is weird. I cannot even reproduce this with net-dns/ldns-utils-1.6.17

**Comment by csmk** [comment]
I'm sorry for the delay, I forgot to mention that the build fail when in combination with the "example" USE flag.

**Comment by csmk** [comment]
I'll PR another version with the freebsd patch.

**Pull request closed without merging**
