### PR TITLE
Bump LibreSSL 3.2.7,3.3.5. Drop LibreSSL 3.4.0

### PR DESCRIPTION
**Pull request by itZzenXX**

### CODE REVIEW

**Comment by CaseOf** [comment]
I think you forgot LibreSSL 3.4.0 in your commit.
Also, I think it should be better to mask than removing it.

**Comment by itZzenXX** [comment]
How would I go about doing that? LibreSSL 3.4.0 has a vulnerability within it, so yeah I think masking it and waiting for a new dev release would be a better sollution here.

**Comment by CaseOf** [comment]
Do you have the CVE reference about it?

**Comment by itZzenXX** [comment]
there is an errata patch for it on OpenBSD's website, should I apply that patch to 3.4.0?

**Comment by CaseOf** [comment]
To fix the CVE?

**Comment by itZzenXX** [comment]
yeah

**Comment by CaseOf** [comment]
of course, add it asap

**Comment by itZzenXX** [comment]
ok, let me make a new pull request that bumps LibreSSL and patches 3.4.0

**Comment by CaseOf** [comment]
yeah with -r1

**Comment by CaseOf** [comment]
Do a git mv if you can to remove the vulnerable version

**Comment by CaseOf** [comment]
and update profile/package.mask

**Comment by itZzenXX** [comment]
alright, on it

**Comment by CaseOf** [comment]
keep the mask on 3.4.0 and add one to 3.4.0-r1, people with 3.4.0 installed must know why it’s masked, and that is affected by a CVE

**Comment by orbea** [comment]
If anyone knows any packages that are currently failing please report them, thanks!

**Pull request closed without merging**
