### PR TITLE
nodejs-6.11.5 version bump

### PR DESCRIPTION
**Pull request by KenjiBrown**
Ebuild from Gentoo portage added RESTRICT="test" after EAPI=6
The rest is the same ebuild as for 6.9.4.

### CODE REVIEW

**Comment by csmk** [comment]
Hmm... You should've created another branch for cargo.

**Comment by KenjiBrown** [comment]
cargo-0.22.0-libressl-2.6.3 
https://bugs.gentoo.org/626272

**Comment by KenjiBrown** [comment]
Sorry, I pushed another commit for cargo and pull requests were merged together.

**Comment by csmk** [comment]
> Sorry, I pushed another commit for cargo and pull requests were merged together.

Yeah, this does happen if you commit to master. Next time try to create branches, so you can make separated PRs. 😉

**Comment by blueness** [comment]
pushed

**Pull request closed without merging**
