### PR TITLE
Use 'libressl' USE flag instead of virtual/openssl

### PR DESCRIPTION
**Pull request by hasufell**
This has several advantages:
* more explicit control, less breakage by missynced virtuals or
  switching the provider
* subslots work correctly

Currently, we don't add a '!dev-libs/openssl:0' blocker to
dev-libs/libressl to be able to test all packages.
However, this should be done when importing it into the tree.

### CODE REVIEW

**Comment by hasufell** [comment]
@blueness @hannob  lala

**Comment by blueness** [comment]
I mentioned on the list that I think a USE flag is the way to go for the reasons you give.

**Comment by blueness** [comment]
A while back I wondered if it wasn't meaningful to add a USE expand flag for ssl providers gentoo wide the way I did for curl.  I don't want to tie the two issues, but something to think about in this context.

+	ssl? (
+	!libressl? ( dev-libs/openssl:0 )
+	libressl? ( dev-libs/libressl:= )
+	)

**Comment by hasufell** [comment]
Well, the problem I see is that we currently have 3 ssl providers but they don't behave in the same way
* gnutls - can be installed at the same time as openssl/libressl
* openssl - can be installed at the same time as gnutls, but nut libressl
* libressl - can be installed at the same time as gnutls, but nut openssl

that really sucks

**Comment by mgorny** [comment]
Plus a random mixture of crypto libs which are sometimes provided by the SSL provider and sometimes need to be provided elsewhere…

**Comment by blueness** [comment]
There is also polarssl and axtls which are meant for embedded systems.  curl can use those.  There's also cyassl which I used to maintain before it started to suck.  I don't know.  Just throwing the idea out there as a way of making sense of the zoo of ssl providers now.  There may be no clean way of dealing.

**Pull request merged**
