### PR TITLE
Drop old versions and add some new ones

### PR DESCRIPTION
**Pull request by dg98**
This completes the work of #297. I dropped dev-qt/qtnetwork-5.11.3 since it was dropped from the main repo already and was causing issues. 
I also removed dev-util/cargo since it's included in dev-lang/rust(-bin) now and isn't available in the main repo anymore and I rebased the changes necessary to make sys-cluster/ceph to build with libressl to newer ebuilds because the one in here wasn't valid anymore according to repoman. Luckily newer versions in the main repo include libressl support now, so maybe we can drop it from here soon.

### CODE REVIEW

**Comment by blueness** [comment]
There are some conflicts with this and #297.  Can clean up this up and resubmit the pull request.  I'm not sure what happened.

**Comment by dg98** [comment]
I merged my branch with @aidanharris's new commits, but for some reason the CI is still failing. I don't see that I did something wrong though.

**Comment by blueness** [comment]
Maybe recreate patch and apply it against a fresh clone.  Make sure to give attribution to @aidanharris as well as yourself.

**Comment by dg98** [comment]
I created a new pull request. Hopefully it's valid now.

**Pull request closed without merging**
